### ISSUE TITLE
Missing TRA V/J combinations in generated repertoires

### ISSUE THREAD

**Issue by ejackson054** [statbiophys/soNNia#13]
Hi, I recently used SONNIA to generate large numbers of post-selection TRA and TRB (10 million each) with your default models for human_T_alpha and human_T_beta, respectively.  For TCRa, we noticed that there are hundreds of V/J gene combinations that are never generated (despite high generation rates for the V and J genes individually).  One example is TRAV3 and TRAJ41:  V frequency is 0.3%, J frequency is 1.6%, for an expected frequency of around 0.0048%.  However, out of 10 million TRA generated, where you would therefore expect roughly 480 TRA with this combination, we did not see any.
 
For this example (TRAV3 and TRAJ41), we checked VDJDB, and found 10 published human TRA chains with this combination. We also found VDJDB results for several other missing V/J combinations, suggesting they are not biologically forbidden.
 
Do you have an explanation for this?  Is it an intentional feature of your model, or is it a technical artifact, for example if the TRA sequences used to train SONNIA did not contain that particular combination?

Thanks so much for any help!

**Comment by giulioisac** [comment]
Hello! The default inferred model has both Pgen and Ppost zero for that VJ gene combination. This could be specific to the individual I used to infer the model. In this case, no sequences used to train the Igor model (already at Pgen) had that VJ combination. Due to individual variability in the V(D)J recombination machinery, it could be that a model inferred on another individual will have a higher probability for that VJ gene combination and will then have a non-zero inferred probability for the Igor model.  The best solution here would be to re-infer a Pgen and Ppost model on your data (if you have it).

**Comment by ejackson054** [comment]
Hi, thanks so much for your quick and helpful response!  One more question:  Are you able to point me to the specific datasets used to train the default human_T_alpha and human_T_beta models? (Apologies if this info is somewhere in the documentation; I checked the repos and publications but was not able to find it.)

**Comment by giulioisac** [comment]
Good question. I haven't included it. The human_T_beta model comes from an individual from the Emerson 2017 dataset https://www.nature.com/articles/ng.3822 . The human_T_alpha instead comes from one of the twins in https://www.pnas.org/doi/full/10.1073/pnas.1809642115. The paper has only TCR_beta but I asked the authors and they had also the light chain. Hope it helps.
